# Site settings
name: Christian Sherland
title: Christian Sherland | Full-stack Software Engineer
description: NYC Based Software engineer
url: https://christiansherland.com
baseurl: ''
email: christiansherland@gmail.com
resume: #
social:
  - title: email
    url: mailto:christiansherland@gmail.com
  - title: github
    url: https://github.com/csherland
  - title: linkedin
    url: https://www.linkedin.com/in/christian-sherland-0785725b/

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'LICENSE.md'

plugins:
  - jekyll-sitemap
  - jemoji
