# Site settings
name: Christian Sherland
title: Christian Sherland | Full-stack Software Engineer
description: NYC Based Software engineer
url: https://csherland.github.io/
baseurl: ''
email: christiansherland@gmail.com
logo: http://google.com
resume: http://google.com
social:
  - title: email
    url: mailto:christiansherland@gmail.com
  - title: github
    url: https://github.com/csherland
  - title: linkedin
    url: https://www.linkedin.com/in/###

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'LICENSE.md'

plugins_dir:
  - jekyll-sitemap
