# Site settings
title: Christian Sherland
url: http://csherland.github.io
author: Christian Sherland
description: Me

# Social info
github_username: csherland
email_address: christiansherland@gmail.com

# Build settings
markdown: kramdown
markdown_ext: md

# Styles
sass:
  sass_dir: css
  style: :compressed
