# Site settings
title: Christian Sherland
description: >
  Cool guy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christiansherland.me" # the base hostname & protocol for your site

# Contact and social info
email: christiansherland@gmail.com
twitter_username: csherland
github_username:  csherland

# Build settings
markdown: kramdown

# Gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
