# Site settings
title:          Christian Sherland
description:    Cool guy.
baseurl:        /
url:            http://csherland.github.io

# Contact and social info
author:
  name:               Christian Sherland
  email:              christiansherland@gmail.com
  twitter_username:   csherland
  github_username:    csherland

# Build settings
markdown: kramdown

# Permalinks
permalink:            pretty
relative_permalinks:  true

# Gems
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
