# Site settings
title: Christian Sherland
description: Me
url: http://christiansherland.me
baseurl: ""
twitter_username: csherland
github_username: csherland
author: Christian Sherland

# Styles
sass:
  sass_dir: css
  style: :compressed
